defaults:
  - scope:
      path: "research/non-analytic-induction/summary"
    values:
      non_analytic_induction_summary: true
  - scope:
      path: "research/non-analytic-induction"
    values:
      non_analytic_induction: true
permalink: /blog/:year-:month-:day-:title:output_ext
title: "Anders Lundstedt" # for feeds
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - "Makefile"
  - "TODO.md"
  - "css.css.view"
  - "flake.lock"
  - "flake.nix"
  - "test.html"
