defaults:
  - scope:
      path: "research/non_analytic_induction/summary"
    values:
      non_analytic_induction_summary: true
permalink: /blog/:year-:month-:day-:title:output_ext
title: "Anders Lundstedt" # for feeds
plugins:
  - jekyll-feed
  - jekyll-seo-tag
